/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="webworker"/>

import { build, files, prerendered, version } from '$service-worker';

declare const self: ServiceWorkerGlobalScope;

const CACHE = `cache-${version}`;

const ASSETS = [
  ...build,      // Files generated by the builder
  ...files,      // Files in the static directory
  ...prerendered // Prerendered pages
];

self.addEventListener('install', (event) => {
  async function addFilesToCache() {
    const cache = await caches.open(CACHE);
    await cache.addAll(ASSETS);
  }

  event.waitUntil(addFilesToCache());
});

self.addEventListener('activate', (event) => {
  async function deleteOldCaches() {
    const keys = await caches.keys();
    for (const key of keys) {
      if (key !== CACHE) {
        await caches.delete(key);
      }
    }
  }

  event.waitUntil(deleteOldCaches());
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

  const url = new URL(event.request.url);

  // Don't intercept dynamic backend/API fetches or DevServer HMR requests
  const isHttp = url.protocol === 'http:' || url.protocol === 'https:';
  const isDevelopment = url.hostname === 'localhost' && url.port !== '';
  const isOurOrigin = url.origin === self.origin;

  if (!isHttp || (isDevelopment && url.pathname.startsWith('/@fs')) || !isOurOrigin) return;

  event.respondWith(
    (async () => {
      const isAsset = ASSETS.includes(url.pathname);
      const cache = await caches.open(CACHE);

      if (isAsset) {
        const cachedResponse = await cache.match(url.pathname);
        if (cachedResponse) {
          return cachedResponse;
        }
      }

      try {
        const response = await fetch(event.request);
        
        // Cache the newly fetched request for offline use
        if (response.status === 200) {
          cache.put(event.request, response.clone());
        }
        
        return response;
      } catch (err) {
        const cachedResponse = await cache.match(event.request);
        if (cachedResponse) {
          return cachedResponse;
        }
        
        // If navigating to a page offline, fall back to index route
        if (event.request.mode === 'navigate') {
          const fallback = await cache.match('/');
          if (fallback) return fallback;
        }

        throw err;
      }
    })()
  );
});
